apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-stack.yml -o kompose
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: database
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-stack.yml -o kompose
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: database
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_DATABASE
              value: example-database
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: example
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
          image: mongo:5
          livenessProbe:
            exec:
              command:
                - '[ `echo ''db.runCommand("ping").ok'' | mongo localhost/example-database --quiet` ] && echo 0 || echo 1'
            failureThreshold: 3
            periodSeconds: 5
            timeoutSeconds: 5
          name: database
          ports:
            - containerPort: 27017
          resources: {}
          # volumeMounts:
          #   - mountPath: /run/secrets/mongo_root
          #     name: mongo_root
          #   - mountPath: /run/secrets/mongo_root_password
          #     name: mongo_root_password
      restartPolicy: Always
      # volumes:
      #   - name: mongo_root
      #     secret:
      #       items:
      #         - key: mongo_root
      #           path: mongo_root
      #       secretName: mongo_root
      #   - name: mongo_root_password
      #     secret:
      #       items:
      #         - key: mongo_root_password
      #           path: mongo_root_password
      #       secretName: mongo_root_password
status: {}
