apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-stack.yml -o kompose
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
spec:
  ports:
    - name: "27017"
      # indicates the port on which the service is accessible (using it's IP address)
      # whithin the cluster
      port: 27017
      # indicates on which port the service should forward the request on the pods
      # (it's the same defined in the deployment config file)
      targetPort: 27017
  selector:
    io.kompose.service: database
status:
  loadBalancer: {}
