apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-stack.yml -o kompose
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 3000
  selector:
    io.kompose.service: server
status:
  loadBalancer: {}
