apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-stack.yml -o kompose
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: database
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-stack.yml -o kompose
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: database
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                # defined inside database-secret.yaml
                secretKeyRef:
                  name: database-secret
                  key: default-database
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: database-password
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: database-user
          image: mongo:5
          livenessProbe:
            exec:
              command:
                - '[ `echo ''db.runCommand("ping").ok'' | mongo localhost/example-database --quiet` ] && echo 0 || echo 1'
            failureThreshold: 10
            periodSeconds: 30
            timeoutSeconds: 30
          name: database
          ports:
            - containerPort: 27017
          resources: {}
      restartPolicy: Always
status: {}
